repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint

  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: task fmt
        language: system
        pass_filenames: false
        types: [go]

      - id: go-vet
        name: go vet
        entry: task vet
        language: system
        pass_filenames: false
        types: [go]

      - id: go-build
        name: go build
        entry: task build
        language: system
        pass_filenames: false
        types: [go]

      - id: go-test
        name: go test
        entry: task test
        language: system
        pass_filenames: false
        types: [go]

      - id: helm-lint
        name: helm lint
        entry: helm lint charts/gatus-controller
        language: system
        pass_filenames: false
        files: ^charts/
