package controller

import (
	"context"
	"testing"

	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	clientgoscheme "k8s.io/client-go/kubernetes/scheme"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"

	monitoringv1alpha1 "github.com/Wihrt/gatus-ingress-controller/api/v1alpha1"
)

func newEndpointTestScheme(t *testing.T) *fake.ClientBuilder {
	t.Helper()
	s := newTestScheme(t)
	_ = clientgoscheme.AddToScheme(s)
	return fake.NewClientBuilder().WithScheme(s)
}

// TestGatusEndpointReconciler_UserManagedWinsOverAutoGenerated verifies that when two
// GatusEndpoint CRs share the same spec.name, the user-managed one (no ownerReferences)
// is written to the ConfigMap and the auto-generated one (has ownerReferences) is skipped.
func TestGatusEndpointReconciler_UserManagedWinsOverAutoGenerated(t *testing.T) {
	ctx := context.Background()
	s := newTestScheme(t)

	cm := &corev1.ConfigMap{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "gatus-config",
			Namespace: "gatus",
		},
		Data: map[string]string{
			"config.yaml": "web:\n  port: 8080\n",
		},
	}

	// Auto-generated CR — has ownerReferences pointing to a parent Ingress.
	autoEndpoint := &monitoringv1alpha1.GatusEndpoint{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "my-app-my-app-example-com",
			Namespace: "default",
			Labels: map[string]string{
				managedByLabel: "gatus-ingress-controller",
				ingressLabel:   "my-app",
			},
			OwnerReferences: []metav1.OwnerReference{
				{APIVersion: "networking.k8s.io/v1", Kind: "Ingress", Name: "my-app"},
			},
		},
		Spec: monitoringv1alpha1.GatusEndpointSpec{
			Name:  "My App",
			Group: "auto",
			URL:   "https://my-app.example.com",
			Conditions: []string{"[STATUS] == 200"},
		},
	}

	// User-managed CR — same spec.name, NO ownerReferences.
	userEndpoint := &monitoringv1alpha1.GatusEndpoint{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "my-app-custom",
			Namespace: "default",
			// No OwnerReferences.
		},
		Spec: monitoringv1alpha1.GatusEndpointSpec{
			Name:  "My App",        // same Gatus display name
			Group: "user-override", // different group — this is what should win
			URL:   "https://my-app.example.com",
			Conditions: []string{"[STATUS] == 200", "[RESPONSE_TIME] < 500"},
		},
	}

	fakeClient := fake.NewClientBuilder().
		WithScheme(s).
		WithObjects(cm, autoEndpoint, userEndpoint).
		Build()

	r := &GatusEndpointReconciler{
		Client:          fakeClient,
		Scheme:          s,
		TargetNamespace: "gatus",
		ConfigMapName:   "gatus-config",
	}

	req := ctrl.Request{NamespacedName: types.NamespacedName{Name: "my-app-custom", Namespace: "default"}}
	_, err := r.Reconcile(ctx, req)
	if err != nil {
		t.Fatalf("Reconcile returned error: %v", err)
	}

	updated := &corev1.ConfigMap{}
	if err := fakeClient.Get(ctx, types.NamespacedName{Name: "gatus-config", Namespace: "gatus"}, updated); err != nil {
		t.Fatalf("ConfigMap not found: %v", err)
	}

	endpointsYAML, ok := updated.Data["endpoints.yaml"]
	if !ok {
		t.Fatal("endpoints.yaml key not found in ConfigMap")
	}

	// The user-override group must appear; the auto group must NOT appear.
	if !contains(endpointsYAML, "user-override") {
		t.Errorf("expected 'user-override' group in endpoints.yaml, got:\n%s", endpointsYAML)
	}
	if contains(endpointsYAML, "group: auto") {
		t.Errorf("auto-generated group 'auto' must not appear in endpoints.yaml, got:\n%s", endpointsYAML)
	}
	// Only one entry for "My App" should be present.
	if count(endpointsYAML, "name: My App") != 1 {
		t.Errorf("expected exactly 1 'My App' entry in endpoints.yaml, got:\n%s", endpointsYAML)
	}
}

// TestGatusEndpointReconciler_WritesConfigMap verifies the basic happy path:
// all GatusEndpoint CRs are written into the ConfigMap under endpoints.yaml.
func TestGatusEndpointReconciler_WritesConfigMap(t *testing.T) {
	ctx := context.Background()
	s := newTestScheme(t)

	cm := &corev1.ConfigMap{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "gatus-config",
			Namespace: "gatus",
		},
		Data: map[string]string{
			"config.yaml": "web:\n  port: 8080\n",
		},
	}

	ep := &monitoringv1alpha1.GatusEndpoint{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "my-endpoint",
			Namespace: "default",
		},
		Spec: monitoringv1alpha1.GatusEndpointSpec{
			Name:       "My Service",
			Group:      "prod",
			URL:        "https://service.example.com",
			Conditions: []string{"[STATUS] == 200"},
		},
	}

	fakeClient := fake.NewClientBuilder().
		WithScheme(s).
		WithObjects(cm, ep).
		Build()

	r := &GatusEndpointReconciler{
		Client:          fakeClient,
		Scheme:          s,
		TargetNamespace: "gatus",
		ConfigMapName:   "gatus-config",
	}

	req := ctrl.Request{NamespacedName: types.NamespacedName{Name: "my-endpoint", Namespace: "default"}}
	_, err := r.Reconcile(ctx, req)
	if err != nil {
		t.Fatalf("Reconcile returned error: %v", err)
	}

	updated := &corev1.ConfigMap{}
	if err := fakeClient.Get(ctx, types.NamespacedName{Name: "gatus-config", Namespace: "gatus"}, updated); err != nil {
		t.Fatalf("ConfigMap not found: %v", err)
	}

	endpointsYAML, ok := updated.Data["endpoints.yaml"]
	if !ok {
		t.Fatal("endpoints.yaml key not found in ConfigMap")
	}
	if !contains(endpointsYAML, "My Service") {
		t.Errorf("expected 'My Service' in endpoints.yaml, got:\n%s", endpointsYAML)
	}
	if !contains(endpointsYAML, "prod") {
		t.Errorf("expected group 'prod' in endpoints.yaml, got:\n%s", endpointsYAML)
	}
}

// TestGatusEndpointReconciler_RequeuesWhenConfigMapMissing verifies that reconciliation
// is requeued (not errored) when the target ConfigMap does not exist yet.
func TestGatusEndpointReconciler_RequeuesWhenConfigMapMissing(t *testing.T) {
	ctx := context.Background()
	s := newTestScheme(t)

	ep := &monitoringv1alpha1.GatusEndpoint{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "my-endpoint",
			Namespace: "default",
		},
		Spec: monitoringv1alpha1.GatusEndpointSpec{
			Name: "My Service",
			URL:  "https://service.example.com",
		},
	}

	fakeClient := fake.NewClientBuilder().
		WithScheme(s).
		WithObjects(ep). // No ConfigMap — intentionally absent.
		Build()

	r := &GatusEndpointReconciler{
		Client:          fakeClient,
		Scheme:          s,
		TargetNamespace: "gatus",
		ConfigMapName:   "gatus-config",
	}

	req := ctrl.Request{NamespacedName: types.NamespacedName{Name: "my-endpoint", Namespace: "default"}}
	result, err := r.Reconcile(ctx, req)
	if err != nil {
		t.Fatalf("Reconcile must not return an error when ConfigMap is missing, got: %v", err)
	}
	if result.RequeueAfter == 0 {
		t.Error("expected RequeueAfter > 0 when ConfigMap is missing")
	}
}

func contains(s, substr string) bool {
	return len(s) > 0 && len(substr) > 0 && (func() bool {
		for i := 0; i <= len(s)-len(substr); i++ {
			if s[i:i+len(substr)] == substr {
				return true
			}
		}
		return false
	})()
}

func count(s, substr string) int {
	n := 0
	for i := 0; i <= len(s)-len(substr); i++ {
		if s[i:i+len(substr)] == substr {
			n++
			i += len(substr) - 1
		}
	}
	return n
}
