apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gatus-ingress-controller.fullname" . }}
  labels:
    {{- include "gatus-ingress-controller.labels" . | nindent 4 }}
rules:
  - apiGroups: ["monitoring.gatus.io"]
    resources: ["gatusalerts", "gatusendpoints", "gatusexternalendpoints", "gatusannouncements", "gatusalertingconfigs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["monitoring.gatus.io"]
    resources: ["gatusalerts/status", "gatusendpoints/status", "gatusexternalendpoints/status", "gatusannouncements/status", "gatusalertingconfigs/status"]
    verbs: ["get", "update", "patch"]
