apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gatus-ingress-controller.fullname" . }}
  labels:
    {{- include "gatus-ingress-controller.labels" . | nindent 4 }}
rules:
  - apiGroups: ["monitoring.gatus.io"]
    resources: ["gatusendpoints", "gatusexternalendpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["monitoring.gatus.io"]
    resources: ["gatusendpoints/status", "gatusexternalendpoints/status"]
    verbs: ["get", "update", "patch"]
