apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gatus-ingress-controller.fullname" . }}
  labels:
    {{- include "gatus-ingress-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gatus-ingress-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gatus-ingress-controller.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "gatus-ingress-controller.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: INGRESS_CLASS
              value: {{ .Values.ingressClass | quote }}
            - name: TARGET_NAMESPACE
              value: {{ .Values.targetNamespace | quote }}
            - name: CONFIG_MAP_NAME
              value: {{ .Values.configMapName | quote }}
            - name: GATEWAY_API_ENABLED
              value: {{ .Values.gatewayApi.enabled | quote }}
            - name: GATEWAY_NAMES
              value: {{ .Values.gatewayApi.gatewayNames | quote }}
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
            - name: health
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
