apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "gatus-ingress-controller.fullname" . }}
  namespace: {{ .Values.targetNamespace }}
  labels:
    {{- include "gatus-ingress-controller.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["{{ .Values.secretName }}"]
    verbs: ["get", "update", "patch"]
