{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "gatus-ingress-controller.fullname" . }}
  labels:
    {{- include "gatus-ingress-controller.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "gatus-ingress-controller.fullname" . }}-webhook-tls
webhooks:
  - name: vgatusendpoint.kb.io
    admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: {{ include "gatus-ingress-controller.fullname" . }}-webhook
        namespace: {{ .Release.Namespace }}
        path: /validate-monitoring-gatus-io-v1alpha1-gatusendpoint
    rules:
      - apiGroups: ["monitoring.gatus.io"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["gatusendpoints"]
    sideEffects: None
    failurePolicy: Fail
{{- end }}
